### ISSUE TITLE
no-unused-modules does not work with shebangs

### ISSUE THREAD

**Issue by ehmicky** [import-js/eslint-plugin-import#1369]
`index.js`:

```js
#!/usr/bin/env node
import { example } from './foo.js'
export { example }
```

`foo.js`:

```js
export const example = true
```

`.eslintrc.yml`:

```yml
parserOptions:
  ecmaVersion: 2019
  sourceType: module
plugins: [import]
rules:
  import/no-unused-modules: [2, {unusedExports: true}]
```

Then:

```bash
$ eslint
/home/user/example/foo.js
  1:1  error  exported declaration 'example' not used within other modules  import/no-unused-modules

✖ 1 problem (1 error, 0 warnings)
```

However this works when removing `#!/usr/bin/env node`.

`eslint`: `5.16.0`
`eslint-plugin-import`: `2.17.3`
`node`: `12.3.1`
OS: Ubuntu `19.04`
