### ISSUE TITLE
'no-unused-modules' doest not take effect on ts/tsx

### ISSUE THREAD

**Issue by stekovinbranturry** [import-js/eslint-plugin-import#1976]
package versions:

```
    "eslint": "7.7.0",
    "eslint-import-resolver-typescript": "2.3.0",
    "eslint-plugin-import": "2.22.1",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.3.0",
```

.eslintrc.yml
```yml
extends:
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript

plugins:
  - '@typescript-eslint'
  - import

settings:
  react:
    version: 16.12.0
  'import/core-modules':
    - '@SDFoundation'
    - '@cms'
    - '@SDCss'
    - '@SDV'
  'import/parsers':
    '@typescript-eslint/parser':
      - '.ts'
      - '.tsx'
  'import/resolver':
    typescript:
      alwaysTryTypes: true
      project: './'
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
      moduleDirectory: ['src/']

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:import/errors'
      - 'plugin:import/warnings'
      - 'plugin:import/typescript'
    rules:
      'no-use-before-define': 0
      #typescript
      '@typescript-eslint/no-use-before-define':
        - error
        - functions: false
      '@typescript-eslint/no-explicit-any': 0
      '@typescript-eslint/no-empty-function': 0
      '@typescript-eslint/no-this-alias': 0

rules:
  import/no-named-as-default-member: 0
  import/default: 0
  import/namespace: 0
```

But 'no-unused-modules' doest not take effect on my ts/tsx files
