### ISSUE TITLE
Mark package as internal not working

### ISSUE THREAD

**Issue by KostyaZgara** [import-js/eslint-plugin-import#2176]
I'm experiencing the issue when can't use the setting `import/internal-regex` to mark my packages as internal. After some manipulation and researching seems the reason is PnP mode which I'm using on my project.

My eslint config
```yaml
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  project: 'tsconfig.json'
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
env:
  node: true
root: true
rules:
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - type
      newlines-between: never
settings:
  import/resolver: typescript
  import/internal-regex: ^@(lib|app)/
```

This configuration linting my code but doesn't recognize marked internal packages. When I remove `import/resolver: typescript` from `settings` it groups my imports in the right way, but throws an error `Resolve error: unable to load resolver "node"  import/order`. The same situation with the default `node` resolver. Seems like when resolver is working it ignores any settings.

My tools:
```
yarn -v
3.0.0

node -v
v14.17.0
```

```json
"eslint": "7.32.0",
"eslint-plugin-import": "2.23.4",
"@typescript-eslint/eslint-plugin": "4.28.5",
"@typescript-eslint/parser": "4.28.5",
"eslint-import-resolver-node": "0.3.4",
"eslint-import-resolver-typescript": "2.4.0",
```

Thanks in advance!

P.S. If you need to provide additional information, please inform me about it
