### ISSUE TITLE
Typescript Docs Question

### ISSUE THREAD

**Issue by Nfinished** [import-js/eslint-plugin-import#2586]
The following bit is unclear to me.

```
# TypeScript

You may use the following shortcut or assemble your own config using the granular settings described below.

Make sure you have installed [`@typescript-eslint/parser`] and [`eslint-import-resolver-typescript`] which are used in the following configuration.

```yaml
extends:
  - eslint:recommended
  - plugin:import/recommended
# the following lines do the trick
  - plugin:import/typescript
settings:
  import/resolver:
    # You will also need to install and configure the TypeScript resolver
    # See also https://github.com/import-js/eslint-import-resolver-typescript#configuration
    typescript: true
    node: true


[`@typescript-eslint/parser`]: https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser
[`eslint-import-resolver-typescript`]: https://github.com/import-js/eslint-import-resolver-typescript
```

Does "You may use the following shortcut" and "the following lines do the trick" indicate that `plugin:import/typescript` should preclude any other configuration? Or do I still need to add the configuration outlined in https://github.com/import-js/eslint-import-resolver-typescript#configuration

Thank you!
