### ISSUE TITLE
Better express `import/order`'s `alphabetize` setting

### ISSUE THREAD

**Issue by aryzing** [import-js/eslint-plugin-import#2786]
Wouldn't it be easier if the order settings first referenced what is being ordered, and then how it is being ordered, rather than how it is currently?

Proposal,

```yaml
rules:
  import/order:
    - error
    - paths: asc
      kind: asc
      someOtherPart: someOtherOrder
```

Compare to how is currently,

```yaml
rules:
  import/order:
    - error
    - alphabetize:
        order: asc
        orderImportKind: asc
        someOtherPart: someOtherOrder # doesn't make sense under alphabetize
```
