### ISSUE TITLE
`import/namespace` failures when importing chai@5

### ISSUE THREAD

**Issue by timbeadle** [import-js/eslint-plugin-import#2949]
Upgrading from chai v4 to chai v5 yields the following eslint error:

```shell
cfpathcheck/test/cfpathcheck.spec.js
  1:24  error  Parse errors in imported module 'chai': Unexpected token ; (146:10)  import/namespace
```

The line of code in question is as follows:
```javascript
import { expect } from 'chai';
```

For now I have added an ignore annotation to my code so that the linting passes, but it would be good to know why the `import/namespace` rule has started to fail with this new, ESM-only, version of chai.

Thank you 😸

**Comment by ljharb** [comment]
What’s your eslint config? A parse error is not expected.

**Comment by timbeadle** [comment]
> What’s your eslint config? A parse error is not expected.

```yaml
env:
  browser: true
  es6: true
extends:
  - xo
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - import
  - redos
rules:
  arrow-parens: 0
  object-curly-spacing: 0
  import/no-unresolved: [2]
  redos/no-vulnerable: error
overrides:
- files:
  - "**/*.spec.js"
  rules:
    redos/no-vulnerable: 'off'
```
